version: '3'
services:
  runner:
    build: .
    environment:
      - GITHUB_PAT=${GITHUB_PAT}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
    deploy:
      replicas: 3
    mem_limit: 100MB